// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKd3tzj9dIVNt4gDKQ-cpjuBfF7JPLRkk',
    appId: '1:376486507942:web:0b8badeb0d23fd26984b67',
    messagingSenderId: '376486507942',
    projectId: 'ditonton-b6a52',
    authDomain: 'ditonton-b6a52.firebaseapp.com',
    storageBucket: 'ditonton-b6a52.appspot.com',
    measurementId: 'G-RJ3EMFYFFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtv_TXySBGoIgIyPBKQ52-VJ9apDPgXqA',
    appId: '1:376486507942:android:ae53afbc80d7ca6e984b67',
    messagingSenderId: '376486507942',
    projectId: 'ditonton-b6a52',
    storageBucket: 'ditonton-b6a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxiWCVEuyabbmdKm81a8M0PEvJVJLULZg',
    appId: '1:376486507942:ios:5dd7a6f0f3b65b64984b67',
    messagingSenderId: '376486507942',
    projectId: 'ditonton-b6a52',
    storageBucket: 'ditonton-b6a52.appspot.com',
    iosBundleId: 'com.example.ditonton',
  );
}
